# permissions for end users to view helloworldren.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helloworld-viewer-role
rules:
- apiGroups:
  - test.desistdaydream.ltd
  resources:
  - helloworldren
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - test.desistdaydream.ltd
  resources:
  - helloworldren/status
  verbs:
  - get
