# permissions for end users to view etcdoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcdoperator-viewer-role
rules:
- apiGroups:
  - test.desistdaydream.ltd
  resources:
  - etcdoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - test.desistdaydream.ltd
  resources:
  - etcdoperators/status
  verbs:
  - get
